server:
  port: 8077
wechat:
  appId:  #'微信公众平台_appID'
  secret:  #'微信公众平台_appsecret'
  userId:  #'微信公众平台_微信号'
  templateId:  #'微信公众平台_模板id'
  district_id:   #'百度地图开放平台_城市ID'
  ak:  #'百度地图开放平台_应用AK'
  loveDate: '2022-08-19'
  birthday: '2004-04-10'
  rainbowKey:  #'彩虹屁平台_apiKey'
